[snowflake]
user="jwestbrockIQR"
password="Eagl3s@031501"
account="VNKZTXN-OU44575"
warehouse="COMPUTE_WH"
database="LMEAQPL_ET_GCP_US_EAST_4_EXTERNAL_TABLES_WZWXE_SECURE_SHARE"
schema="AMAZON_SP_API"
